### ISSUE TITLE
Crash when opening on Mac

### ISSUE THREAD

**Issue by pettitjr** [firstlookmedia/dangerzone#71]
App crashed immediately on startup when attempting to open. Behavior is consistent whether attempting to open on its own, or using "Open With" dialog on PDF. 
Console shows application exiting with a code 255, and sometimes with a code 2. 

 Running Mojave 10.14.6. Cons

**Comment by micahflee** [comment]
Can you open a terminal and run dangerzone like this?

```
/Applications/Dangerzone.app/Contents/MacOS/dangerzone
```

If it crashes again and shows an error message, can you copy and paste the error message in a comment here?

**Comment by pettitjr** [comment]
Here you go!

$ /Applications/Dangerzone.app/Contents/MacOS/dangerzone
dangerzone 0.1
Temporary directories created, dangerous=/tmp/dangerzone-pixel-r7louort, safe=/tmp/dangerzone-safe-vh3ny8wg
Traceback (most recent call last):
  File "install/pyinstaller/dangerzone", line 4, in <module>
  File "click/core.py", line 764, in __call__
  File "click/core.py", line 717, in main
  File "click/core.py", line 956, in invoke
  File "click/core.py", line 555, in invoke
  File "dangerzone/__init__.py", line 54, in main
  File "dangerzone/global_common.py", line 77, in __init__
  File "dangerzone/global_common.py", line 326, in _find_pdf_viewers
FileNotFoundError: [Errno 2] No such file or directory: '/System/Library/Contents/Info.plist'
[61283] Failed to execute script dangerzone

**Comment by pettitjr** [comment]
Looks like it was a bug in 0.1. I just downloaded 0.1.1 from dangerzone.rocks, and it's working. It did bomb out when trying to download and install Docker, but I was able to get around that by downloading and installing Docker separately. 

Sorry for the confusion, and thanks for putting this tool together!
