### ISSUE TITLE
Crash when opening on macOS Catalina 10.15.2 

### ISSUE THREAD

**Issue by rorymbyrne** [firstlookmedia/dangerzone#76]
Crash when opening on macOS Catalina 10.15.2 

Output on /Applications/Dangerzone.app/Contents/MacOS/dangerzone

Temporary directories created, dangerous=/tmp/dangerzone-pixel-0_p6ti1m, safe=/tmp/dangerzone-safe-6rjdauv4
Traceback (most recent call last):
  File "install/pyinstaller/dangerzone", line 4, in <module>
  File "click/core.py", line 764, in __call__
  File "click/core.py", line 717, in main
  File "click/core.py", line 956, in invoke
  File "click/core.py", line 555, in invoke
  File "dangerzone/gui.py", line 51, in gui_main
  File "dangerzone/global_common.py", line 68, in __init__
  File "dangerzone/global_common.py", line 372, in _find_pdf_viewers
KeyError: 'CFBundleName'
[23599] Failed to execute script dangerzone

**Comment by micahflee** [comment]
I think this is related to a specific PDF reader package you have installed, and should be fixed in the next release because of https://github.com/firstlookmedia/dangerzone/pull/75
