### ISSUE TITLE
[BUG] Application fails when checking thirdparty application's Info.plist without CFBundleName [macOS 10.15.6]

### ISSUE THREAD

**Issue by andrewcrook** [firstlookmedia/dangerzone#85]
First time user of Dangerzone

macOS 10.15.6 (19G73)
MBP 13" 2019 i7 16GB
Docker for Desktop Mac pre installed  - version 2.3.0.3 (45519)

installed from brew also tried from dmg image.

Open Dangerzone Application or using "open with" from finder on PDF file.
Application opens but does show any GUI and ends straight away, almost instant.
No container(s) found under Docker dashboard. 
No crash report dialogue raised

No crash log under console
system.log under console has the following information  
```
Jul 22 11:11:46 Andrews-MBP com.apple.xpc.launchd[1] (com.apple.xpc.launchd.oneshot.0x10000001.dangerzone[753]): Service exited with abnormal code: 2
Jul 22 11:14:10 Andrews-MBP com.apple.xpc.launchd[1] (media.firstlook.dangerzone.60064[978]): Service exited with abnormal code: 255
Jul 22 11:18:59 Andrews-MBP com.apple.xpc.launchd[1] (media.firstlook.dangerzone.60064[833]): Service exited with abnormal code: 255
```

**Comment by andrewcrook** [comment]
I managed to get a trace-back

`Temporary directories created, dangerous=/tmp/dangerzone-pixel-6uf5vgch, safe=/tmp/dangerzone-safe-6105vm2v
Traceback (most recent call last):
  File "install/pyinstaller/dangerzone", line 4, in <module>
  File "click/core.py", line 764, in __call__
  File "click/core.py", line 717, in main
  File "click/core.py", line 956, in invoke
  File "click/core.py", line 555, in invoke
  File "dangerzone/gui.py", line 51, in gui_main
  File "dangerzone/global_common.py", line 68, in __init__
  File "dangerzone/global_common.py", line 372, in _find_pdf_viewers
KeyError: 'CFBundleName'
[24339] Failed to execute script dangerzone`

which is the line

`if plist_dict.get("CFBundleName") and plist_dict["CFBundleName"] != "Dangerzone":
                    pdf_viewers[plist_dict["CFBundleName"]] = bundle_identifier`

I have found that you cannot take for granted that an application will have the key pair CFBundleName (Bundle name) under their Info.plist. I found such an application called Typinator (since raised the issue with them)

Might I suggest writing a conditional for if the dictionary key does or doesn’t exist before looking at the value?
May be also look for sub-strings in the Bundle identifier (CFBundleIdentifier) as well ?

**Comment by andrewcrook** [comment]
I see #75 has a possible solution  the one mentioned above
